// Chess puzzle library (v2) — backed by the curated lichess import.
//
// `library.json` is generated by scripts/import-lichess-puzzles.mjs from the
// CC0 lichess open puzzle database: ~4.9k puzzles, 350 in each 100-point rating
// bucket from 500–1900, filtered to short/instructive tactics + mates and
// re-validated with chess.js. Each entry is stored compactly as
// `{ f: fen, m: [uci…], r: rating, k: 'mate'|'tactic' }`.
//
// The lichess move convention (preserved here): `moves[0]` is the OPPONENT's
// setup move (animated first), and `moves[1..]` is the solution line —
// odd indices are the KID's moves, even indices are the opponent's replies.
// So a single-move puzzle is `moves.length === 2` (one kid reply); a mate-in-2
// is `moves.length === 4` (kid, opp, kid); etc.
//
// The whole library is re-checked by scripts/validate-chess-puzzles.mjs
// (every line legal from the FEN; mate lines end in checkmate).

import libraryRaw from './library.json';

export type PuzzleKind = 'mate' | 'tactic';

export interface ChessPuzzle {
  fen: string;
  /** UCI moves. [0] = opponent setup; odd = kid's moves, even = opponent replies. */
  moves: string[];
  /** Lichess Glicko rating — the difficulty axis the adaptive ladder ramps on. */
  rating: number;
  kind: PuzzleKind;
}

interface RawPuzzle {
  f: string;
  m: string[];
  r: number;
  k: PuzzleKind;
}

/** The full library, mapped from the compact on-disk shape. */
export const PUZZLES: ChessPuzzle[] = (libraryRaw as RawPuzzle[]).map((p) => ({
  fen: p.f,
  moves: p.m,
  rating: p.r,
  kind: p.k,
}));

/** How many moves the KID must play to solve this puzzle. */
export function kidMoveCount(p: ChessPuzzle): number {
  return Math.ceil((p.moves.length - 1) / 2);
}

/** Kid-facing headline for the puzzle. */
export function puzzleGoal(p: ChessPuzzle): string {
  const n = kidMoveCount(p);
  if (p.kind === 'mate') return n > 1 ? `Checkmate in ${n}!` : 'Find checkmate!';
  return n > 1 ? 'Win with a combo!' : 'Win the piece!';
}

/** Gentle hint (shown after a wrong try): which piece to move at this ply. */
export function puzzleHint(p: ChessPuzzle, ply: number): string {
  const from = p.moves[ply]?.slice(0, 2);
  return from ? `Look at the piece on ${from}.` : 'Find the strongest move.';
}
