// Maze With Gates — config types, helpers, and the kid-designed Crayon Maze.
//
// A different mechanic from Math Maze:
//   - Math Maze: you tap cells that satisfy a rule; the math IS the movement.
//   - Maze With Gates: you walk freely through a maze; the math is a BARRIER
//     at specific "gate" cells. Reach a gate → a challenge modal opens →
//     answer correctly → the gate unlocks and you can pass through it.
//
// This file is pure TypeScript — no React, no DOM, no Supabase. The config
// type is designed to be JSON-serializable so the future game-creator
// pipeline (spec §7) can emit one from a kid's drawing and parent approval,
// and this same renderer will play it.
//
// Source: inspired by a founding kid's hand-drawn maze (2026-04-11).
// She drew a freeform orange-marker maze with ~9 math gates and instructions
// "Answer correctly, you might go in that direction." This config is a
// grid-quantized interpretation of that drawing, not a pixel reproduction.
// Her specific math problems are preserved in their approximate order.

import { generateMathChallenge, type MathType } from '@/lib/games/shared/generate-challenge';
import { isConceptType } from '@/lib/games/shared/generate-concept-challenge';
import type { MathKind } from '@/lib/games/shared/challenge-mode';

// ---------------------------------------------------------------------------
// Types
// ---------------------------------------------------------------------------

export interface MazeGatesPosition {
  row: number;
  col: number;
}

/** Cell types. Each grid cell is exactly one of these.
 *  `start` and `end` are walkable (the character stands on them); they're
 *  distinct from `path` only so we can render markers and pick them up
 *  without a separate coordinate lookup. */
export type Cell = 'wall' | 'path' | 'gate' | 'start' | 'end';

/** A challenge the kid must answer to unlock a gate.
 *  Tagged union so different challenge types can be added without breaking
 *  existing configs. `numeric` carries a pre-rendered prompt + answer so it can
 *  hold any operation generated by generateMathChallenge (add/sub/mult/mixed). */
export type Challenge =
  | { type: 'addition'; a: number; b: number }
  | { type: 'numeric'; prompt: string; answer: number };

export function challengeAnswer(c: Challenge): number {
  switch (c.type) {
    case 'addition':
      return c.a + c.b;
    case 'numeric':
      return c.answer;
  }
}

/** Human-readable prompt for the challenge modal. */
export function challengePrompt(c: Challenge): string {
  switch (c.type) {
    case 'addition':
      return `${c.a} + ${c.b}`;
    case 'numeric':
      return c.prompt;
  }
}

export interface GateDef {
  id: string;
  position: MazeGatesPosition;
  challenge: Challenge;
}

/** Theme controls the visual feel. Hand-drawn aesthetic is the whole point
 *  of this template — expose the colors as config so the same renderer
 *  can theme different mazes differently (per kid-designed maze, or custom). */
export interface MazeGatesTheme {
  playerGlyph: string;           // emoji for the player character
  wallColor: string;             // CSS color for rough-drawn wall strokes
  gateColor: string;             // unsolved gate fill/stroke
  gateSolvedColor: string;       // solved gate fill/stroke
  pathColor: string;             // subtle path hint
  backgroundColor: string;       // "paper" color
  accentColor: string;           // start/end markers, highlights
}

export interface MazeGatesConfig {
  version: 1;
  title: string;
  /** Who designed this game. Rendered in the UI header as a "by the designer kid"
   *  byline so the kid sees their name on their own game. */
  designer?: string;
  theme: MazeGatesTheme;
  grid: {
    rows: number;
    cols: number;
    cells: Cell[][]; // cells[row][col]
  };
  start: MazeGatesPosition;
  end: MazeGatesPosition;
  gates: GateDef[];
}

// ---------------------------------------------------------------------------
// Pure helpers (renderer + logic)
// ---------------------------------------------------------------------------

export function positionsEqual(a: MazeGatesPosition, b: MazeGatesPosition): boolean {
  return a.row === b.row && a.col === b.col;
}

export function isAdjacent(a: MazeGatesPosition, b: MazeGatesPosition): boolean {
  const dr = Math.abs(a.row - b.row);
  const dc = Math.abs(a.col - b.col);
  return (dr === 1 && dc === 0) || (dr === 0 && dc === 1);
}

export function cellAt(
  config: MazeGatesConfig,
  pos: MazeGatesPosition,
): Cell | undefined {
  const { rows, cols, cells } = config.grid;
  if (pos.row < 0 || pos.row >= rows) return undefined;
  if (pos.col < 0 || pos.col >= cols) return undefined;
  return cells[pos.row]?.[pos.col];
}

export function gateAt(
  config: MazeGatesConfig,
  pos: MazeGatesPosition,
): GateDef | undefined {
  return config.gates.find((g) => positionsEqual(g.position, pos));
}

/**
 * Can the character step INTO this cell? Walls are never passable. Path /
 * start / end are always passable. A gate is passable only once its
 * challenge has been solved — otherwise stepping into it triggers the
 * challenge modal but does NOT actually move the character.
 */
export function isPassable(
  config: MazeGatesConfig,
  pos: MazeGatesPosition,
  solvedGates: ReadonlySet<string>,
): boolean {
  const cell = cellAt(config, pos);
  if (cell === undefined || cell === 'wall') return false;
  if (cell === 'gate') {
    const gate = gateAt(config, pos);
    return gate ? solvedGates.has(gate.id) : false;
  }
  return true; // path | start | end
}

// ---------------------------------------------------------------------------
// Session summary (for the /api/attempts POST body)
// ---------------------------------------------------------------------------

export interface MazeGatesSessionSummary {
  taps_total: number;
  taps_wrong: number;
  optimal_taps: number;
  efficiency: number;
  completed: boolean;
  session_ms: number;
}

/**
 * Derive a session summary for the adaptive engine.
 *
 * "Efficiency" here is `gates_solved / (gates_solved + wrong_answers)`.
 * A perfect run (answered every gate right on the first try) scores 1.0.
 * A sloppy run (wrong answers along the way) scores lower.
 *
 * Movement taps (walking through already-open corridor) are NOT counted —
 * they aren't educational, only the challenge answers are. This matches
 * how Math Maze defines efficiency for its mechanic and keeps the server
 * side mastery function agnostic to which template produced the score.
 */
export function summarizeMazeSession(args: {
  gatesTotal: number;
  gatesSolved: number;
  wrongAnswers: number;
  completed: boolean;
  sessionMs: number;
}): MazeGatesSessionSummary {
  const optimal = args.gatesTotal;
  const total = args.gatesSolved + args.wrongAnswers;
  const efficiency = total > 0 ? args.gatesSolved / total : 0;
  return {
    taps_total: total,
    taps_wrong: args.wrongAnswers,
    optimal_taps: optimal,
    efficiency,
    completed: args.completed,
    session_ms: args.sessionMs,
  };
}

// ---------------------------------------------------------------------------
// Grid builder — construct a MazeGatesConfig from a path array
// ---------------------------------------------------------------------------
//
// Rather than hand-drawing an ASCII grid (error-prone, hard to reason
// about connectivity), we describe the maze by listing the SEQUENCE of
// cells along the main path from start to end. Everything off the path
// becomes a wall. Gate positions are specified by index into that path.
// This guarantees connectivity by construction and makes the design
// readable — the TypeScript literal describes the path you actually walk.

interface PathGateSpec {
  /** Zero-based index into the path array. Index 0 is start, last is end.
   *  Don't place gates at index 0 or at the last index. */
  pathIndex: number;
  challenge: Challenge;
}

function buildConfigFromPath(args: {
  rows: number;
  cols: number;
  path: readonly (readonly [number, number])[];
  gates: readonly PathGateSpec[];
  title: string;
  designer?: string;
  theme: MazeGatesTheme;
}): MazeGatesConfig {
  const { rows, cols, path, gates, title, designer, theme } = args;

  // Validate path
  if (path.length < 2) throw new Error('path must have at least 2 cells');
  for (const [r, c] of path) {
    if (r < 0 || r >= rows || c < 0 || c >= cols) {
      throw new Error(`path cell out of bounds: (${r},${c})`);
    }
  }
  // Validate adjacency
  for (let i = 1; i < path.length; i++) {
    const [r1, c1] = path[i - 1];
    const [r2, c2] = path[i];
    const dr = Math.abs(r1 - r2);
    const dc = Math.abs(c1 - c2);
    if (!((dr === 1 && dc === 0) || (dr === 0 && dc === 1))) {
      throw new Error(`path cells ${i - 1} and ${i} are not orthogonally adjacent: (${r1},${c1}) → (${r2},${c2})`);
    }
  }

  // Start with all walls
  const cells: Cell[][] = Array.from({ length: rows }, () =>
    Array.from({ length: cols }, () => 'wall' as Cell),
  );

  // Paint the path
  for (const [r, c] of path) {
    cells[r][c] = 'path';
  }

  // Mark gates
  const gateDefs: GateDef[] = [];
  for (let i = 0; i < gates.length; i++) {
    const spec = gates[i];
    if (spec.pathIndex <= 0 || spec.pathIndex >= path.length - 1) {
      throw new Error(`gate ${i} pathIndex ${spec.pathIndex} must be between 1 and ${path.length - 2}`);
    }
    const [r, c] = path[spec.pathIndex];
    cells[r][c] = 'gate';
    gateDefs.push({
      id: `g${i + 1}`,
      position: { row: r, col: c },
      challenge: spec.challenge,
    });
  }

  // Start / end overrides
  const [sr, sc] = path[0];
  const [er, ec] = path[path.length - 1];
  cells[sr][sc] = 'start';
  cells[er][ec] = 'end';

  return {
    version: 1,
    title,
    designer,
    theme,
    grid: { rows, cols, cells },
    start: { row: sr, col: sc },
    end: { row: er, col: ec },
    gates: gateDefs,
  };
}

// ---------------------------------------------------------------------------
// the kid-designed maze — the hand-coded config
// ---------------------------------------------------------------------------
//
// 14 rows × 10 cols, portrait orientation. Start at bottom-left (13,1),
// end near top-right (0,8). Path winds up through the maze in an S-shape
// with several branches collapsed into the main corridor.
//
// The 9 gates use the specific math problems the designer kid wrote on her
// drawing: 5+6, 4+8, 10+2, 2+4, 11+6, 9+1, 4+4, 3+4, 3+3. The order
// along the path goes from easiest (3+3=6 near the start) to hardest
// (11+6=17 and the two =12 problems near the end), matching the natural
// progression a kid would want.

const CRAYON_PATH: readonly (readonly [number, number])[] = [
  // Bottom corridor, going right
  [13, 1], [13, 2], [13, 3], [13, 4], [13, 5],
  // Up
  [12, 5],
  // Go left across row 11
  [11, 5], [11, 4], [11, 3], [11, 2],
  // Up to row 10, then right across
  [10, 2], [10, 3], [10, 4], [10, 5], [10, 6], [10, 7],
  // Up the right side
  [9, 7], [8, 7], [7, 7],
  // Left across row 7
  [7, 6], [7, 5], [7, 4],
  // Up
  [6, 4],
  // Right on row 5
  [5, 4], [5, 5], [5, 6],
  // Up
  [4, 6],
  // Left across row 3
  [3, 6], [3, 5], [3, 4], [3, 3], [3, 2],
  // Up
  [2, 2],
  // Right all the way across row 1 to the end column
  [1, 2], [1, 3], [1, 4], [1, 5], [1, 6], [1, 7], [1, 8],
  // Final step up to the END
  [0, 8],
];

const CRAYON_GATES: readonly PathGateSpec[] = [
  { pathIndex: 4,  challenge: { type: 'addition', a: 3,  b: 3  } }, // 6
  { pathIndex: 8,  challenge: { type: 'addition', a: 3,  b: 4  } }, // 7
  { pathIndex: 13, challenge: { type: 'addition', a: 4,  b: 4  } }, // 8
  { pathIndex: 17, challenge: { type: 'addition', a: 9,  b: 1  } }, // 10
  { pathIndex: 21, challenge: { type: 'addition', a: 2,  b: 4  } }, // 6
  { pathIndex: 25, challenge: { type: 'addition', a: 5,  b: 6  } }, // 11
  { pathIndex: 29, challenge: { type: 'addition', a: 11, b: 6  } }, // 17 — her hardest
  { pathIndex: 33, challenge: { type: 'addition', a: 4,  b: 8  } }, // 12
  { pathIndex: 37, challenge: { type: 'addition', a: 10, b: 2  } }, // 12
];

const CRAYON_THEME: MazeGatesTheme = {
  playerGlyph: '🦊',
  // Warm orange matching her marker
  wallColor: '#e8744b',
  gateColor: '#e8744b',
  gateSolvedColor: '#4caf50',
  pathColor: '#fef3c7',
  // Slightly off-white paper feel
  backgroundColor: '#fffaf0',
  accentColor: '#166534',
};

// Dead-end branches — cells to carve OUT of the wall so the maze feels
// like a real maze (twists + dead ends + choices) per the designer kid's ticket
// "I want this to be a real maze." Each cell listed below becomes a walkable
// `path` cell; since any adjacent `path` cells are connected, listing the
// right cells creates branches off the main corridor that end in dead ends.
// None of these contain gates — they exist purely for exploration.
const CRAYON_DEAD_ENDS: readonly (readonly [number, number])[] = [
  // Short branch up from the bottom corridor at col 3 → 2 deep
  [12, 3], [11, 3],
  // Branch up from row 10 at col 4 → 2 deep
  [9, 4], [8, 4],
  // Branch down from row 7 col 5 → short
  [8, 5],
  // L-shaped dead end from row 5 → up and left
  [4, 5], [4, 4], [4, 3],
  // Branch down from row 1 col 4 → 1 deep (quick detour)
  [2, 4],
  // Branch off row 11 extending left to make the west side twistier
  [11, 1], [12, 1],
];

function withDeadEnds(
  config: MazeGatesConfig,
  cells: readonly (readonly [number, number])[],
): MazeGatesConfig {
  const nextCells = config.grid.cells.map((row) => [...row]);
  for (const [r, c] of cells) {
    if (nextCells[r]?.[c] === 'wall') {
      nextCells[r][c] = 'path';
    }
  }
  return { ...config, grid: { ...config.grid, cells: nextCells } };
}

export const CRAYON_MAZE: MazeGatesConfig = withDeadEnds(
  buildConfigFromPath({
    rows: 14,
    cols: 10,
    path: CRAYON_PATH,
    gates: CRAYON_GATES,
    title: 'Crayon Maze',
    designer: 'a Gamecakes kid',
    theme: CRAYON_THEME,
  }),
  CRAYON_DEAD_ENDS,
);

// ---------------------------------------------------------------------------
// Tier-scaled generator — same proven (connected) layout as the kid-designed maze,
// but each gate's problem is generated for the kid's tier + chosen operation
// via the shared generateMathChallenge. Problems vary per run.
// ---------------------------------------------------------------------------

/** Gates in this maze are answered on a numeric keypad — the local Challenge
 *  union above has no choice variant — so a concept domain (shapes, time,
 *  comparison) cannot be rendered here. GameLauncher hides those kinds for
 *  maze games via `arithmeticOnly`; this coercion is the belt to that braces,
 *  and it degrades to mixed arithmetic rather than emitting an unanswerable
 *  gate. */
export function generateMazeForTier(tier: number, kind: MathKind = 'mixed'): MazeGatesConfig {
  const mathType: MathType = isConceptType(kind) ? 'mixed' : kind;
  const gates: PathGateSpec[] = CRAYON_GATES.map((g) => {
    const ch = generateMathChallenge(tier, mathType);
    return {
      pathIndex: g.pathIndex,
      challenge: { type: 'numeric', prompt: ch.prompt, answer: ch.answer } as Challenge,
    };
  });
  return withDeadEnds(
    buildConfigFromPath({
      rows: 14,
      cols: 10,
      path: CRAYON_PATH,
      gates,
      title: 'Crayon Maze',
      designer: 'a Gamecakes kid',
      theme: CRAYON_THEME,
    }),
    CRAYON_DEAD_ENDS,
  );
}
