// Generate and verify the open-source baseline schema (PRD phase 2.3).
//
//   SUPABASE_ACCESS_TOKEN=sbp_... node scripts/opensource/baseline.mjs generate <ref> > supabase/baseline/0001_baseline.sql
//   SUPABASE_ACCESS_TOKEN=sbp_... node scripts/opensource/baseline.mjs fingerprint <ref>
//
// Talks to the Supabase Management API over HTTPS rather than connecting to
// Postgres directly, because db.<ref>.supabase.co is IPv6-only and pg_dump is
// frequently unavailable on a dev box.
//
// WHY GENERATE FROM THE LIVE DATABASE rather than from supabase/migrations/*:
//
//   1. Those files are not a reliable description of the schema. They have
//      always been applied by hand in the dashboard SQL editor -- the CLI's
//      supabase_migrations.schema_migrations table has never contained the
//      0001-0044 series at all. Migration 0015 was never applied to the
//      founding project while application code queried the column it adds,
//      and nothing detected that for months.
//
//   2. Several of them carry backfills that match the founding family's
//      children BY NAME. Dumping structure cannot carry rows, so a generated
//      baseline is name-clean by construction instead of by careful editing.
//
// The only data emitted is the skills catalog (universal content: no
// family_id, no kid_id) and the storage bucket rows.
//
// VERIFY, always: fingerprint the source project and a scratch project that
// has had the baseline applied, and diff. They must be byte-identical. An
// empty diff proves the baseline reproduces production; a non-empty diff is
// another silent 0015 you have not found yet.

import { readFileSync } from 'node:fs';

const TOKEN = process.env.SUPABASE_ACCESS_TOKEN;
if (!TOKEN) {
  console.error('SUPABASE_ACCESS_TOKEN is not set (a personal access token, sbp_...).');
  console.error('Create one at https://supabase.com/dashboard/account/tokens');
  process.exit(1);
}

const [mode, ref] = process.argv.slice(2);
if (!mode || !ref || !['generate', 'fingerprint'].includes(mode)) {
  console.error('usage: baseline.mjs <generate|fingerprint> <projectRef>');
  process.exit(1);
}

async function q(sql) {
  const res = await fetch(`https://api.supabase.com/v1/projects/${ref}/database/query`, {
    method: 'POST',
    headers: { Authorization: `Bearer ${TOKEN}`, 'Content-Type': 'application/json' },
    body: JSON.stringify({ query: sql }),
  });
  const text = await res.text();
  if (!res.ok) throw new Error(`HTTP ${res.status}: ${text.slice(0, 500)}`);
  return JSON.parse(text);
}

/** Run a single-column query and return the values. */
const col1 = async (sql) => (await q(sql)).map((r) => Object.values(r)[0]);

if (mode === 'fingerprint') {
  const sql = readFileSync(new URL('./fingerprint.sql', import.meta.url), 'utf8');
  console.log((await col1(sql)).sort().join('\n'));
  process.exit(0);
}

const NL = String.fromCharCode(92) + 'n'; // a literal \n inside the SQL strings below

const SQL = {
  functions: `select pg_get_functiondef(p.oid) || E';${NL}'
    from pg_proc p join pg_namespace n on n.oid = p.pronamespace
    where n.nspname = 'public' and p.prokind = 'f' order by p.proname`,

  tables: `select 'CREATE TABLE public.' || quote_ident(c.relname) || E' (${NL}' || string_agg(
      '  ' || quote_ident(a.attname) || ' ' || format_type(a.atttypid, a.atttypmod)
      || case a.attidentity
           when 'a' then ' GENERATED ALWAYS AS IDENTITY'
           when 'd' then ' GENERATED BY DEFAULT AS IDENTITY'
           else coalesce(' DEFAULT ' || pg_get_expr(ad.adbin, ad.adrelid), '') end
      || case when a.attnotnull then ' NOT NULL' else '' end,
      E',${NL}' order by a.attnum) || E'${NL});'
    from pg_class c join pg_namespace n on n.oid = c.relnamespace
    join pg_attribute a on a.attrelid = c.oid and a.attnum > 0 and not a.attisdropped
    left join pg_attrdef ad on ad.adrelid = c.oid and ad.adnum = a.attnum
    where n.nspname = 'public' and c.relkind = 'r'
    group by c.relname order by c.relname`,

  pkeys: `select format('ALTER TABLE public.%I ADD CONSTRAINT %I %s;', cl.relname, c.conname, pg_get_constraintdef(c.oid))
    from pg_constraint c join pg_class cl on cl.oid = c.conrelid join pg_namespace n on n.oid = cl.relnamespace
    where n.nspname = 'public' and c.contype = 'p' order by cl.relname`,

  constraints: `select format('ALTER TABLE public.%I ADD CONSTRAINT %I %s;', cl.relname, c.conname, pg_get_constraintdef(c.oid))
    from pg_constraint c join pg_class cl on cl.oid = c.conrelid join pg_namespace n on n.oid = cl.relnamespace
    where n.nspname = 'public' and c.contype in ('c','u','f')
    order by c.contype desc, cl.relname, c.conname`,

  indexes: `select indexdef || ';' from pg_indexes i where schemaname = 'public'
    and not exists (select 1 from pg_constraint c where c.conname = i.indexname and c.contype in ('p','u'))
    order by tablename, indexname`,

  triggers: `select pg_get_triggerdef(t.oid) || ';' from pg_trigger t
    join pg_class cl on cl.oid = t.tgrelid join pg_namespace n on n.oid = cl.relnamespace
    where n.nspname = 'public' and not t.tgisinternal order by cl.relname, t.tgname`,

  rls: `select format('ALTER TABLE public.%I ENABLE ROW LEVEL SECURITY;', c.relname)
    from pg_class c join pg_namespace n on n.oid = c.relnamespace
    where n.nspname = 'public' and c.relkind = 'r' and c.relrowsecurity order by c.relname`,

  policies: `select format('CREATE POLICY %I ON public.%I AS %s FOR %s TO %s%s%s;',
      policyname, tablename, permissive, cmd, array_to_string(roles, ', '),
      coalesce(E'${NL}  USING (' || qual || ')', ''),
      coalesce(E'${NL}  WITH CHECK (' || with_check || ')', ''))
    from pg_policies where schemaname = 'public' order by tablename, policyname`,
};

/** SQL literal for a JS value pulled back from the Management API. */
const lit = (v) =>
  v === null || v === undefined ? 'NULL'
  : typeof v === 'number' ? String(v)
  : typeof v === 'boolean' ? (v ? 'true' : 'false')
  : typeof v === 'object' ? `'${JSON.stringify(v).replace(/'/g, "''")}'::jsonb`
  : `'${String(v).replace(/'/g, "''")}'`;

const S = {};
for (const [key, sql] of Object.entries(SQL)) S[key] = (await col1(sql)).join('\n');

const skillCols = await col1(
  `select attname from pg_attribute where attrelid = 'public.skills'::regclass
   and attnum > 0 and not attisdropped order by attnum`);
const skills = await q('select * from public.skills order by id');
const buckets = await q('select id, name, public from storage.buckets order by id');

console.log(`-- =====================================================================
-- Gamecakes baseline schema
--
-- Builds the whole database from empty. This REPLACES the 0001-0044 migration
-- series, which is the founding deployment's history and is of no use to
-- anyone else. Migrations after this one are numbered from 0045.
--
-- GENERATED FROM THE LIVE SCHEMA by scripts/opensource/baseline.mjs, not by
-- concatenating those migrations. Two reasons that matters:
--   1. The migration files were never a reliable description of the database.
--      They were applied by hand, and 0015 was never applied at all while the
--      application queried the column it adds.
--   2. Several carry backfills matching the founding family's children BY
--      NAME. A structure dump carries no rows, so this file is name-clean by
--      construction rather than by careful editing.
--
-- The only data below is the skills catalog (universal content: no family_id,
-- no kid_id) and the storage buckets. Everything else starts empty.
--
-- Regenerate and verify:
--   node scripts/opensource/baseline.mjs generate <ref> > supabase/baseline/0001_baseline.sql
--   node scripts/opensource/baseline.mjs fingerprint <sourceRef>  > a.txt
--   node scripts/opensource/baseline.mjs fingerprint <scratchRef> > b.txt   # baseline applied
--   diff a.txt b.txt        # must be empty
-- =====================================================================

-- As pg_dump does: allow a function body to reference a table that does not
-- exist yet, so ordering only has to satisfy hard dependencies.
set check_function_bodies = off;

-- ------------------------------------------------------------- 1. extensions
create extension if not exists "pgcrypto" with schema extensions;
create extension if not exists "uuid-ossp" with schema extensions;

-- -------------------------------------------------------------- 2. functions
-- Ahead of the tables: kids.grade_year DEFAULTs to school_year(), and a
-- default expression must resolve at CREATE TABLE time.
${S.functions}
-- ----------------------------------------------------------------- 3. tables
${S.tables}

-- ----------------------------------------------------------- 4. primary keys
${S.pkeys}

-- ----------------------------------- 5. unique, check and foreign key constraints
${S.constraints}

-- ---------------------------------------------------------------- 6. indexes
${S.indexes}

-- --------------------------------------------------------------- 7. triggers
${S.triggers}

-- ------------------------------------------------------- 8. row level security
-- Some tables below get RLS enabled and NO policy. That is DELIBERATE, not an
-- omission: with RLS on and no policy every client role is denied, and only
-- the server's service_role (which bypasses RLS) can read them. Adding a
-- permissive policy to "fix" one would expose invite codes and parent records.
${S.rls}

-- --------------------------------------------------------------- 9. policies
${S.policies}

-- ------------------------------------------------------- 9b. table privileges
-- CREATE TABLE grants nothing. On a fresh Supabase project the public schema
-- carries default privileges that would cover these, but relying on that is
-- how you get a database whose tables all exist and none of which the app can
-- read -- PostgREST returns 42501 "permission denied for table skills" and the
-- setup script reports an empty catalog. Granting explicitly makes the
-- baseline self-sufficient on any project, including one whose public schema
-- was dropped and recreated.
--
-- Wide table grants are Supabase's model, not an oversight: row level security
-- is the actual gate (section 8), and the production database grants exactly
-- this. The five RLS-enabled tables with no policy stay locked to clients
-- regardless of the grant below, because RLS is evaluated after privileges.
grant usage on schema public to postgres, anon, authenticated, service_role;
grant all on all tables in schema public to postgres, anon, authenticated, service_role;
grant all on all sequences in schema public to postgres, anon, authenticated, service_role;
grant all on all functions in schema public to postgres, anon, authenticated, service_role;

-- And for anything a later migration adds.
alter default privileges in schema public grant all on tables to postgres, anon, authenticated, service_role;
alter default privileges in schema public grant all on sequences to postgres, anon, authenticated, service_role;
alter default privileges in schema public grant all on functions to postgres, anon, authenticated, service_role;

-- -------------------------------------------------------- 10. storage buckets
-- Private, with no storage policies: uploads and reads go through the server
-- using the service key. Parent observation photos and kid feedback
-- attachments break without these.
insert into storage.buckets (id, name, public) values
${buckets.map((b) => `  (${lit(b.id)}, ${lit(b.name)}, ${lit(b.public)})`).join(',\n')}
on conflict (id) do nothing;

-- -------------------------------------------------------------- 11. seed data
-- Skills catalog: ${skills.length} rows. Universal content, no family_id and
-- no kid_id. IDs are preserved so installs are reproducible and anything
-- referencing a skill by id stays stable.
INSERT INTO public.skills (${skillCols.map((c) => `"${c}"`).join(', ')}) VALUES
${skills.map((r) => '  (' + skillCols.map((c) => lit(r[c])).join(', ') + ')').join(',\n')}
ON CONFLICT (id) DO NOTHING;`);
